# permissions for end users to view nodepoolingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodepoolingress-viewer-role
rules:
- apiGroups:
  - apps.openyurt.io
  resources:
  - nodepoolingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.openyurt.io
  resources:
  - nodepoolingresses/status
  verbs:
  - get
