# permissions for end users to edit nodepoolingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodepoolingress-editor-role
rules:
- apiGroups:
  - apps.openyurt.io
  resources:
  - nodepoolingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.openyurt.io
  resources:
  - nodepoolingresses/status
  verbs:
  - get
